services:
  pg18:
    image: postgres:18
    container_name: pg18
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'AAdb'

volumes:
  postgres_data:
